### ISSUE TITLE
Add hover effect on nav bar links

### ISSUE THREAD

**Issue by dipanshparmar** [dipanshparmar/sortvisual#14]
**Is your feature request related to a problem? Please describe.**
Currently, there is no hover effect on navbar links.

**Describe the solution you'd like**
I would like to have some hover effect on the navbar items. Please refer to the below mentioned codepen resource.

**Additional context**
Apply the last effect `/* Highlighted text in */` mentioned at this [codepen](https://codepen.io/EvyatarDa/pen/waKXMd)

**Do not change**
1. code formatting
2. other files
3. font-size of the nav links

**Comment by msraghavganesh** [comment]
I'm planning to work on this issue.

**Comment by dipanshparmar** [comment]
@msraghavganesh sure! please go ahead.
