### ISSUE TITLE
Website is not responsive

### ISSUE THREAD

**Issue by dipanshparmar** [dipanshparmar/sortvisual#3]
**Is your feature request related to a problem? Please describe.**
The website is not responsive for smaller screens right now. It'll be better if users can access the site on mobile screens too.

**Describe the solution you'd like**
Make the site responsive.

**Additional context**
![image](https://user-images.githubusercontent.com/49204837/103473763-3a2db400-4dc2-11eb-9b48-b076190549bc.png)

**Comment by Yossef-Ahmed** [comment]
Assign It to me and I'll make sure that the app is responsive on all screens. and If you let me, I'll replace all the IDs (used in scss) with Classes because IDs shouldn't be used in selectors

Wish to help :)

**Comment by dipanshparmar** [comment]
Yeah @Yossef-Ahmed! please go ahead.

A small suggestion, let the IDs be there and add the classes along with the IDs and update the selectors accordingly.

Thanks :smile:

**Comment by dipanshparmar** [comment]
@Yossef-Ahmed and if you want to hide those algorithm details (time complexities), then please hide it for the screen sizes under 768px :slightly_smiling_face:

**Comment by Yossef-Ahmed** [comment]
Sorry for the late answer but I'll finish it today and make the pull request

**Comment by dipanshparmar** [comment]
Done :heavy_check_mark:
