### ISSUE TITLE
Bars should be aligned in the center

### ISSUE THREAD

**Issue by dipanshparmar** [dipanshparmar/sortvisual#6]
**Is your feature request related to a problem? Please describe.**
Currently, the bars are aligned to the left.

**Describe the solution you'd like**
Bars should be aligned to the center

**Additional context**
![image](https://user-images.githubusercontent.com/49204837/103473957-73672380-4dc4-11eb-9c0e-23a7083ec209.png)

**Comment by meerhamzadev** [comment]
As I see the scss code of the website, you are using flexbox in the visualizer-container so, to align these bars on the center you can change justify-content to center, and a suggestion: you can give some gap between bars.

**Comment by dipanshparmar** [comment]
@MeerHamza1421 Do you want to work on this?

**Comment by meerhamzadev** [comment]
Yeah sure

**Comment by dipanshparmar** [comment]
Thanks, @MeerHamza1421. For now, please align the bars in the center. Maybe we will do the spacing thing shortly :smile:
