### ISSUE TITLE
Sliders UI can be improved

### ISSUE THREAD

**Issue by dipanshparmar** [dipanshparmar/sortvisual#7]
**Is your feature request related to a problem? Please describe.**
Currently, the sliders have a kind of default look

**Describe the solution you'd like**
Sliders can be styled using custom CSS (minor changes only)

**Additional context**
![image](https://user-images.githubusercontent.com/49204837/103474049-b1187c00-4dc5-11eb-9ef8-4e27aa0c17ac.png)

**Comment by rllyhz** [comment]
**Working**
